### ISSUE TITLE
Portal DEV environment is not deploying

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal#244]
### Current Behavior
Recent merges to the portal frontend finished creating images successfully but were not deployed on ArgoCD. It shows an error and manual sync didn't work, too.

### Expected Behavior
After a new docker image is pushed Argo should deploy it automatically within a few minutes.

### Steps To Reproduce
See error message here:
https://argo.dev.demo.catena-x.net/applications/portal?view=tree&resource=&conditions=false

**Comment by evegufy** [comment]
@oyo I analysed and I think the sync is failing due to missing secrets. It's due to the following PR https://github.com/eclipse-tractusx/portal/pull/227 where the following Issues weren't maintained in the vault:
- <path:portal/data/dev/processes-worker#issuercomponent-client-secret> 
-  <path:portal/data/dev/processes-worker#issuercomponent-encryption-key0>
@Phil91 could you please maintain the secrets? (also for int env please)

**Comment by Phil91** [comment]
@oyo the issue is fixed, I did also check on dev. Could you please double check and close the issue if everything looks fine for you?

/cc @evegufy

**Comment by oyo** [comment]
thanks - looks good now
